### ISSUE TITLE
[1.18.2] Dedicated server crash - TownCraft modpack - t de.markusbordihn.dailyrewards.player.PlayerRewardManager.handlePlayerLoggedOutEvent

### ISSUE THREAD

**Issue by ProsperCraft** [MarkusBordihn/BOs-Daily-Rewards#1]
**Describe the bug**
Dedicated server crashed when player timed out.

**Expected behavior**

**Screenshots**

**Debugging**
[Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.
](https://gist.githubusercontent.com/ProsperCraft/3e1f971f2ca31bd3e5a37ead5f5a1b96/raw/92921c66e54b38abb41161c717e6be43da7b079d/gistfile1.txt)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
See crash report

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. The issue should be fixed with version:
https://www.curseforge.com/minecraft/mc-mods/daily-rewards/files/3896153

**Comment by ProsperCraft** [comment]
What a quick fix, thank you!
