### ISSUE TITLE
Daily Rewards kicks players

### ISSUE THREAD

**Issue by LegendaryBosma** [MarkusBordihn/BOs-Daily-Rewards#10]
Hi,

I am trying to use Daily Rewards. I am using daily_rewards_1.16.5-1.0.0.jar
Whenever I try to join the server with the mod installed I get this:
[ERROR] Channels [daily_rewards:network] rejected their client side version number

And on the client side disconnect message:
reason: Connection closed - mismatched mod channel list

I am using 1.16.5 in server aswell.

**Comment by MarkusBordihn** [comment]
Thanks for the report. Could you please link the client and server log with the exact error message?
Normally this means that the versions or the config file are not matching.

You need to make sure to use the same mod version and if you modify something in the config file, that the same config file with the same settings are used on the server and client side.
