### ISSUE TITLE
Permissions Code

### ISSUE THREAD

**Issue by Meidde** [MarkusBordihn/BOs-Daily-Rewards#14]
I use Luckperms, what permission do players need to use the command?
For example in Mod MKUltra the permission to use is mkultra.class
probably your Mod also has a permission

**Comment by MarkusBordihn** [comment]
Mhhh unfortunately the source code of MKUltra is not public available so I'm not able to check this.
But I assume you need to use one of the followings:

- DailyRewards.class
- DailyRewards
- daily_rewards

The mod itself use the Minecraft permission system with permission level 0 (all players):
See: https://github.com/MarkusBordihn/BOs-Daily-Rewards/blob/cf7c9147e7aebfd6e37680d46eff5764f58e5e66/src/main/java/de/markusbordihn/dailyrewards/commands/ClaimCommand.java#L46
