### ISSUE TITLE
Crash and Config Not Applying

### ISSUE THREAD

**Issue by mahjerion** [MarkusBordihn/BOs-Daily-Rewards#16]
MC Version 1.20.1
daily_rewards_1.20.1-4.5.1.jar

**Describe the bug**
Hi Markus, I'm currently making a new pack and I really like the concept of the daily rewards mod. I do have an issue where after I changed the configuration for the mod, my testers would sometimes get a client-side crash. I have attached one of the crash reports to this issue.

Additionally, it seems like the actual reward scheme is not being applied. Even though I've changed the config, I'm still getting the default seeds, diamonds, etc. Oddly enough, when I preview the rewards for following months, it works. I have tried new worlds, and reset the data too as described on the wiki. I've attached the config for reference.

If it's an issue with another mod, I'd be happy to work it out.

**To Reproduce**
Have my config and try loading it I guess?

**Expected behavior**
No GUI crash, and daily rewards that were set are shown.

[config](https://pastebin.com/FG45kssC)
[crash report](https://pastebin.com/cLpqpNau)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the crash log and the config example.
Would it be possible to check if you getting the same kind of crashed with the current "beta" version ?

Regardless of the result with the "beta" version, I will check your config and the crash log more in detail and will get back to you.

**Comment by mahjerion** [comment]
Wow appreciate the quick response. No problem. I'll give the beta version a shot and see how it goes in the meantime!

**Comment by mahjerion** [comment]
I booted up a new world with the config and the beta version and received the following crash:
https://pastebin.com/3pxCr5qH

Seems like the config part is working though after the crash.

**Comment by MarkusBordihn** [comment]
Thanks for the quick update. I think I found the issue and will work on a fix.

**Comment by MarkusBordihn** [comment]
In the next few hours the beta version 5.0.1 should be live. 
Please check if you still experience any crashes with this version, if not I will update the current 4.x version with the fix.

The beta version 5.x has still some bugs and will be released in the next few days.

**Comment by mahjerion** [comment]
Thanks I'll test it once released and post back here

**Comment by mahjerion** [comment]
Seems to work!

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. I updated the former releases versions with the fix.
The beta version will take some days before finalized, but will also include the fix.

Please let me know if you experience any other issue with the mod.
