### ISSUE TITLE
Rewards not updating in claim UI.

### ISSUE THREAD

**Issue by JamZia** [MarkusBordihn/BOs-Daily-Rewards#20]
**Rewards Items not showing.**
running /dailyrewards claim opens the default ui, not the items in config.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. Did you restarted the game / server and  followed the steps to reset the rewards for the current month?
See: https://github.com/MarkusBordihn/BOs-Daily-Rewards/wiki/Configuration#reset-reward-data

If yes, please provide additional details to reproduce the issue.
