### ISSUE TITLE
Shutdown the game when clicking on "open the special reward screen"

### ISSUE THREAD

**Issue by Sheendrah** [MarkusBordihn/BOs-Daily-Rewards#27]
Each time I try to open the special reward screen my game shutdown. Our server is on **Fabric 1.20.1**

**To Reproduce**
1. Type in the chat /DailyRewards test overview OR /DailyRewards test special_overview 
2. On the GUI, click on the chest Top right or Top left
3. Game shutdown 

**Expected behavior**
I thought this should open another GUI with the special rewards

**Screenshots**
![2024-04-12 12_57_49-Minecraft_ 1 20 1 - Multijoueur (serveur tiers)](https://github.com/MarkusBordihn/BOs-Daily-Rewards/assets/147916057/8746b9ab-bf85-4604-95d9-375eaa6e5835)
![2024-04-12 12_58_05-Minecraft_ 1 20 1 - Multijoueur (serveur tiers)](https://github.com/MarkusBordihn/BOs-Daily-Rewards/assets/147916057/d1aaf7e2-944f-4f1d-8987-ecca02116048)

**Debugging**
Here is the log after the shutdown
/DailyRewards test overview => https://mclo.gs/CXxvb7Y
/DailyRewards test special_overview => https://mclo.gs/mxl52oD

**Comment by MarkusBordihn** [comment]
Thanks for the report. The issue should be fix with version 5.3.1 and higher.
