### ISSUE TITLE
[1.16.5]Claim all the rewards whit Quark

### ISSUE THREAD

**Issue by SkullDiamond** [MarkusBordihn/BOs-Daily-Rewards#4]
**Describe the bug**
Using quarks inventory managment you can claim all the rewards.

**To Reproduce**
1. Install quark
2. Use extract button

**Expected behavior**
you claim all the rewards

**Screenshots**
https://imgur.com/a/2X9ANUM

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Quark as far as I know

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report, seems like a known issue with Quark, which not consider the `mayPickup` from the reward slots.
See: https://github.com/MarkusBordihn/BOs-Daily-Rewards/blob/1.16.5/src/main/java/de/markusbordihn/dailyrewards/menu/slots/RewardSlot.java#L44

To solve this please add the following to your **quark-common.toml** config:
`"Ignored Screens" = ["de.markusbordihn.dailyrewards.client.screen.RewardScreen"]`

I will open a PR with Quark to add this directly in their mods deny list.
