### ISSUE TITLE
Command block not work, any compatibility?

### ISSUE THREAD

**Issue by NxelScar** [MarkusBordihn/BOs-Daily-Rewards#6]
Hello! I like so much this mod, but I don't really want users on my server (1.18.2) to type commands, so I tried to make the code run through a npc, but that didn't work, so I tried running it through via a command block, but that didn't work either. It can only be activated through text chat. I'm wondering if I'm making a mistake, if not, could I please consider making the commands compatible with the command block? And so they can will be activated by means of a lever, for example. Thank you very much for taking the time to read me, and congratulations on the fantastic modifications you have made!

**Comment by MarkusBordihn** [comment]
Added documentation at https://github.com/MarkusBordihn/BOs-Daily-Rewards/tree/1.19.4#using-with-command-blocks
