### ISSUE TITLE
Quark compatibility issues

### ISSUE THREAD

**Issue by Orangejewce92** [MarkusBordihn/BOs-Daily-Rewards#7]
Hello,
Found a huge issue with the mod and was hoping you can fix this. With the quark mod installed you can simply press the "down" button in the inventory and collect all the items at once as well as the "checkmarks". the dailyrewards menu is treated like an inventory of a chest or something. truly wish to use this mod but players stealing all the loot in one second!

1.16.5 version

**Comment by MarkusBordihn** [comment]
Thanks for the report, this should be already fixed with https://github.com/MarkusBordihn/BOs-Daily-Rewards/issues/4 and 
I submitted the corresponding fix to the Quark team, please make sure that you use the latest version of Quark.
If this is still not working, please let me know the exact version number of Quark and I'm happy to take a closer look.

You could solve this by adding the following to your quark-common.toml config:
"Ignored Screens" = ["de.markusbordihn.dailyrewards.client.screen.RewardScreen"]

**Comment by Orangejewce92** [comment]
that'd be great if that option was available, i don't see a "ignored screens" portion in the quark-common.toml
Quark Version: Quark-r2.4-322.jar
Which is the latest for MC version 1.16.5

**Comment by Orangejewce92** [comment]
[management]
	"Chests In Boats" = true
	"Easy Transfering" = true
	"Hotbar Changer" = true
	"Inventory Sorting" = true
	"Item Sharing" = true
	"Right Click Armor" = true
	"Shulker Box Right Click" = true

	[management.easy_transfering]
		"Enable Shift Lock" = true

	[management.inventory_sorting]
		"Enable Player Inventory" = true
		"Enable Player Inventory In Chests" = true
		"Enable Chests" = true
		#Play a click when sorting inventories using keybindings
		"Satisfying Click" = true

	[management.item_sharing]
		"Render Items In Chat" = true
		
		
	This is all that's provided for the management section. For now I've set to false "Easy Transferring" - but players like that button.

**Comment by MarkusBordihn** [comment]
Ok, it seems Quark has not back-ported the change and will not back-ported it, so you need to manually add this entry into your `quark-common.toml` file like:
```
[general]
  #A list of screens that don't play well with quark's buttons. Use "Print Screen Classnames" to find the names of any others you'd want to add.
  "Ignored Screens" = ["de.markusbordihn.dailyrewards.client.screen.RewardScreen"]
```

**Comment by Orangejewce92** [comment]
yeah this does not work. You can't just add something to a config file. 
although i did try it to see and it failed.
